# Generated by Django 5.0.6 on 2024-06-10 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_producto',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Tipo')),
                ('nombreTipo', models.CharField(max_length=30, verbose_name='Nombre Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nombreP', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('tipoP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.tipo_producto', verbose_name='Tipo')),
            ],
        ),
    ]
