# Generated by Django 5.0.6 on 2024-06-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_rename_idproducto_producto_id_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ingredientes',
            field=models.TextField(default='Ingredientes por defecto', verbose_name='Ingredientes'),
        ),
    ]
