# Generated by Django 5.0.6 on 2024-06-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_producto_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='idProducto',
            new_name='id_producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombreP',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='tipoP',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='tipo_producto',
            old_name='idTipo',
            new_name='id_tipo',
        ),
        migrations.RenameField(
            model_name='tipo_producto',
            old_name='nombreTipo',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Descripción por defecto', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='Precio'),
        ),
    ]
